name: qbittorrent
services:
  qbittorrent:
    image: studiop/qbittorrent:${QBITTORRENT_VERSION}-${VUETORRENT_VERSION}
    build:
      context: .
      args:
        QBITTORRENT_VERSION: ${QBITTORRENT_VERSION}
        VUETORRENT_VERSION: ${VUETORRENT_VERSION}
      tags:
        - studiop/qbittorrent:${QBITTORRENT_VERSION}-${VUETORRENT_VERSION}
    container_name: qbittorrent
    environment:
      TZ: America/New_York
      UMASK: 000
    entrypoint: /app/qbittorrent-nox
    labels:
      - docker-volume-backup.stop-during-backup=qbt
    volumes:
      - config:/config
      - downloads:/downloads
      - ./init:/custom-cont-init.d:ro
    ports:
      - ${QBT_PORT:-6881}:${QBT_PORT:-6881}
      - ${QBT_PORT:-6881}:${QBT_PORT:-6881}/udp
      - 8017:8080
    restart: unless-stopped
    stop_grace_period: 30s
    networks:
      - qbt-net
    deploy:
      resources:
        limits:
          memory: 4GiB
        reservations:
          cpus: '0.5'
          memory: 1GiB

  backup:
    image: docker.io/offen/docker-volume-backup:v2.49.0
    container_name: qbt-backup
    restart: unless-stopped
    environment:
      AWS_S3_BUCKET_NAME: backup.containers.data
      AWS_S3_PATH: qbittorrent
      AWS_ACCESS_KEY_ID: ${BACKUP_S3_ACCESS_KEY:-backup}
      AWS_SECRET_ACCESS_KEY: ${BACKUP_S3_SECRET_KEY?err}
      AWS_ENDPOINT: ${BACKUP_S3_ENDPOINT:-http://truenas.studiop:9000}
      AWS_ENDPOINT_PROTO: http
      BACKUP_STOP_DURING_BACKUP_LABEL: qbt
    volumes:
      - config:/backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - qbt-net
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 256MiB
        limits:
          memory: 512MiB

networks:
  qbt-net:
    name: qbittorrent

volumes:
  downloads:
    name: downloads
    external: true
  config:
    name: qbt-config
