name: firefox
services:
  firefox:
    image: docker.io/jlesage/firefox:v26.09.1
    ports:
      - 5801-5803:5800
    volumes:
      - /config
      - downloads:/downloads
    restart: unless-stopped
    environment:
      TZ: America/New_York
      UMASK: 000
      KEEP_APP_RUNNING: 1
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      PUID: 1000
      PGID: 1000
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 8GiB
        reservations:
          cpus: '0.5'
          memory: 1GiB
    shm_size: 4GiB
    networks:
      - ff-net

networks:
  ff-net:
    name: firefox
volumes:
  downloads:
    name: downloads
    external: true
