name: firefox
services:
  firefox:
    container_name: firefox-${NUM?err}
    image: docker.io/jlesage/firefox:v26.09.1
    ports:
      - 580${NUM?err}:5800
    volumes:
      - config:/config
      - downloads:/downloads
    restart: unless-stopped
    environment:
      TZ: America/New_York
      UMASK: 000
      KEEP_APP_RUNNING: 1
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      PUID: 1000
      PGID: 1000
    deploy:
      resources:
        limits:
          memory: 8GiB
        reservations:
          cpus: '0.5'
          memory: 1GiB
    shm_size: 4GiB
    networks:
      - ff-net

networks:
  ff-net:
    name: firefox

volumes:
  config:
    name: firefox${NUM?err}-config
  downloads:
    name: downloads
    external: true
