name: libredb
services:
  libredb-studio:
    container_name: libredb-studio
    image: ghcr.io/libredb/libredb-studio:0.16.2
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - db-net
      - admin-net
    deploy:
      resources:
        limits:
          memory: 512MiB
        reservations:
          cpus: '0.5'
          memory: 256MiB

networks:
  db-net:
    name: databases
    external: true
    internal: true
  admin-net:
    name: admin